@startuml
scale 1050 width
hide empty description
[*] --> READY

state READY {
}

state READY_MOUSE_DOWN {
}

state OBJ_ON_RENDERING {
}


state OBJ_SELECTED {

}

state OBJ_GRABBED {

}


state GUIDE_GRABBED {

}

state OBJ_ON_MOVING {

}

state OBJ_ON_RESIZING {

READY --> READY_MOUSE_DOWN: mouseDown
READY_MOUSE_DOWN --> OBJ_SELECTED : mouseUpした座標にobjが見つかった
READY_MOUSE_DOWN --> READY : mouseUpした座標にobjが見つからない
READY_MOUSE_DOWN --> OBJ_ON_RENDERING : mouseMove かつ 変異が閾値以上
OBJ_SELECTED --> OBJ_GRABBED : obj領域内でmouseDown
OBJ_SELECTED --> READY : obj領域外でmouseDown
OBJ_SELECTED --> OBJ_SELECTED : 別obj領域内でmouseDown -> obj切り替え
OBJ_SELECTED --> OBJ_SELECTED : mouseMove(領域内 -> cursor move)
OBJ_SELECTED --> OBJ_SELECTED : mouseMove(領域外 -> cursor normal)
OBJ_SELECTED --> GUIDE_GRABBED : guide領域内でmouseDown
GUIDE_GRABBED --> OBJ_ON_RESIZING : mouseMove
GUIDE_GRABBED --> OBJ_SELECTED : mouseUp
OBJ_ON_RESIZING --> OBJ_SELECTED : mouseUp
OBJ_ON_RESIZING --> OBJ_ON_RESIZING : mouseMove
OBJ_GRABBED --> OBJ_ON_MOVING : mouseMove
OBJ_GRABBED --> OBJ_SELECTED : mouseUp
OBJ_ON_MOVING --> OBJ_SELECTED : mouseUp
OBJ_ON_MOVING --> OBJ_ON_MOVING : mouseMove
OBJ_ON_RENDERING --> OBJ_SELECTED : mouseUp
OBJ_ON_RENDERING --> OBJ_ON_RENDERING : mouseMove


@enduml